=== Balimbo/study/ОИТ/4. XML/ЛР №2/2/scheme.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="scheme.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="in">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="info" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="university"/>
              <xs:element type="xs:short" name="points"/>
              <xs:element type="xs:string" name="plan"/>
              <xs:element type="xs:string" name="city"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Balimbo/study/ОИТ/4. XML/ЛР №1/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<in xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="scheme.xsd">
	<info>
		<university>БГУиР</university>
		<points>356</points>
		<plan>50 человек</plan>
		<city>Минск</city>
	</info>
	<info>
		<university>Другой универ</university>
		<points>401</points>
		<plan>0 человек</plan>
		<city>Дреговичи</city>
	</info>
</in>
